/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as QuemELucioRenatoRouteImport } from './routes/quem-e-lucio-renato'
import { Route as RedesRouteImport } from './routes/redes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UtilidadePublicaRouteImport } from './routes/utilidade-publica'
import { Route as ApiPostsRouteImport } from './routes/api.posts'
import { Route as FotosKeyRouteImport } from './routes/fotos.$key'
import { Route as ApiPostsIdRouteImport } from './routes/api.posts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemELucioRenatoRoute = QuemELucioRenatoRouteImport.update({
  id: '/quem-e-lucio-renato',
  path: '/quem-e-lucio-renato',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesRoute = RedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilidadePublicaRoute = UtilidadePublicaRouteImport.update({
  id: '/utilidade-publica',
  path: '/utilidade-publica',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosKeyRoute = FotosKeyRouteImport.update({
  id: '/fotos/$key',
  path: '/fotos/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIdRoute = ApiPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/parceiros': typeof ParceirosRoute
  '/quem-e-lucio-renato': typeof QuemELucioRenatoRoute
  '/redes': typeof RedesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/utilidade-publica': typeof UtilidadePublicaRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/fotos/$key': typeof FotosKeyRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/parceiros': typeof ParceirosRoute
  '/quem-e-lucio-renato': typeof QuemELucioRenatoRoute
  '/redes': typeof RedesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/utilidade-publica': typeof UtilidadePublicaRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/fotos/$key': typeof FotosKeyRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/parceiros': typeof ParceirosRoute
  '/quem-e-lucio-renato': typeof QuemELucioRenatoRoute
  '/redes': typeof RedesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/utilidade-publica': typeof UtilidadePublicaRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/fotos/$key': typeof FotosKeyRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/conteudos'
    | '/parceiros'
    | '/quem-e-lucio-renato'
    | '/redes'
    | '/sitemap.xml'
    | '/utilidade-publica'
    | '/api/posts'
    | '/fotos/$key'
    | '/api/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/conteudos'
    | '/parceiros'
    | '/quem-e-lucio-renato'
    | '/redes'
    | '/sitemap.xml'
    | '/utilidade-publica'
    | '/api/posts'
    | '/fotos/$key'
    | '/api/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/conteudos'
    | '/parceiros'
    | '/quem-e-lucio-renato'
    | '/redes'
    | '/sitemap.xml'
    | '/utilidade-publica'
    | '/api/posts'
    | '/fotos/$key'
    | '/api/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ConteudosRoute: typeof ConteudosRoute
  ParceirosRoute: typeof ParceirosRoute
  QuemELucioRenatoRoute: typeof QuemELucioRenatoRoute
  RedesRoute: typeof RedesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UtilidadePublicaRoute: typeof UtilidadePublicaRoute
  ApiPostsRoute: typeof ApiPostsRouteWithChildren
  FotosKeyRoute: typeof FotosKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-e-lucio-renato': {
      id: '/quem-e-lucio-renato'
      path: '/quem-e-lucio-renato'
      fullPath: '/quem-e-lucio-renato'
      preLoaderRoute: typeof QuemELucioRenatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes': {
      id: '/redes'
      path: '/redes'
      fullPath: '/redes'
      preLoaderRoute: typeof RedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilidade-publica': {
      id: '/utilidade-publica'
      path: '/utilidade-publica'
      fullPath: '/utilidade-publica'
      preLoaderRoute: typeof UtilidadePublicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos/$key': {
      id: '/fotos/$key'
      path: '/fotos/$key'
      fullPath: '/fotos/$key'
      preLoaderRoute: typeof FotosKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$id': {
      id: '/api/posts/$id'
      path: '/$id'
      fullPath: '/api/posts/$id'
      preLoaderRoute: typeof ApiPostsIdRouteImport
      parentRoute: typeof ApiPostsRoute
    }
  }
}

interface ApiPostsRouteChildren {
  ApiPostsIdRoute: typeof ApiPostsIdRoute
}

const ApiPostsRouteChildren: ApiPostsRouteChildren = {
  ApiPostsIdRoute: ApiPostsIdRoute,
}

const ApiPostsRouteWithChildren = ApiPostsRoute._addFileChildren(
  ApiPostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ConteudosRoute: ConteudosRoute,
  ParceirosRoute: ParceirosRoute,
  QuemELucioRenatoRoute: QuemELucioRenatoRoute,
  RedesRoute: RedesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UtilidadePublicaRoute: UtilidadePublicaRoute,
  ApiPostsRoute: ApiPostsRouteWithChildren,
  FotosKeyRoute: FotosKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
